language: objective-c
xcode_project: PropertyComposition.xcodeproj
xcode_scheme: PropertyComposition-OSX
osx_image: xcode7.2
before_install: true
install: true
git:
  submodules: false
script:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.9.4/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - /usr/local/bin/carthage bootstrap --platform Mac
  - xctool -project PropertyComposition.xcodeproj -scheme PropertyComposition-OSX
  - xcodebuild test -project PropertyComposition.xcodeproj -scheme PropertyComposition-OSX